### ISSUE TITLE
WhatsApp Icon not available in social menu

### ISSUE THREAD

**Issue by prajumali** [andersnoren/rowling#2]
WhatsApp Icon not available in social menu. Need to add WhatsApp SVG icon to themes core.

**Comment by andersnoren** [comment]
Hi @prajumali,

I don't have any plans on adding additional social icons to my legacy themes, but you can add them through a child theme or the Additional CSS field in the Customizer.

This is how the CSS for adding a social icon looks in the theme stylesheet:

```
.social-menu a[href*="spotify.com"]::before { content: '\f1bc'; font-family: 'Font Awesome 5 Brands'; }
```

Change the `href*=""` to match WhatsApp links, add the [FontAwesome code](https://fontawesome.com/icons/whatsapp?f=brands&s=solid) for the WhatsApp icon to the `content` property, and you should be good to go. You might need to add an updated version of FontAwesome if the WhatsApp icon isn't included in the version of the FontAwesome font bundled with Rowling.

— Anders
